abstract final class PrayerCountryNames {
  static const Map<String, Map<String, String>> _names = {
    'ar': {
      'AD': "أندورا",
      'AE': "الإمارات العربية المتحدة",
      'AF': "أفغانستان",
      'AG': "أنتيغوا وبربودا",
      'AI': "أنغويلا",
      'AL': "ألبانيا",
      'AM': "أرمينيا",
      'AO': "أنغولا",
      'AR': "الأرجنتين",
      'AS': "ساموا الأمريكية",
      'AT': "النمسا",
      'AU': "أستراليا",
      'AW': "أروبا",
      'AX': "جزر آلاند",
      'AZ': "أذربيجان",
      'BA': "البوسنة والهرسك",
      'BB': "بربادوس",
      'BD': "بنغلاديش",
      'BE': "بلجيكا",
      'BF': "بوركينا فاسو",
      'BG': "بلغاريا",
      'BH': "البحرين",
      'BI': "بوروندي",
      'BJ': "بنين",
      'BL': "سان بارتليمي",
      'BM': "برمودا",
      'BN': "بروناي",
      'BO': "بوليفيا",
      'BR': "البرازيل",
      'BS': "جزر البهاما",
      'BT': "بوتان",
      'BW': "بوتسوانا",
      'BY': "بيلاروس",
      'BZ': "بليز",
      'CA': "كندا",
      'CD': "الكونغو - كينشاسا",
      'CF': "جمهورية أفريقيا الوسطى",
      'CG': "الكونغو - برازافيل",
      'CH': "سويسرا",
      'CI': "ساحل العاج",
      'CK': "جزر كوك",
      'CL': "تشيلي",
      'CM': "الكاميرون",
      'CN': "الصين",
      'CO': "كولومبيا",
      'CR': "كوستاريكا",
      'CU': "كوبا",
      'CV': "الرأس الأخضر",
      'CW': "كوراساو",
      'CY': "قبرص",
      'CZ': "التشيك",
      'DE': "ألمانيا",
      'DJ': "جيبوتي",
      'DK': "الدانمرك",
      'DM': "دومينيكا",
      'DO': "جمهورية الدومينيكان",
      'DZ': "الجزائر",
      'EC': "الإكوادور",
      'EE': "إستونيا",
      'EG': "مصر",
      'ER': "إريتريا",
      'ES': "إسبانيا",
      'ET': "إثيوبيا",
      'FI': "فنلندا",
      'FJ': "فيجي",
      'FM': "ميكرونيزيا",
      'FO': "جزر فارو",
      'GA': "الغابون",
      'GB': "المملكة المتحدة",
      'GD': "غرينادا",
      'GE': "جورجيا",
      'GG': "غيرنزي",
      'GH': "غانا",
      'GL': "غرينلاند",
      'GM': "غامبيا",
      'GN': "غينيا",
      'GQ': "غينيا الاستوائية",
      'GR': "اليونان",
      'GS': "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      'GT': "غواتيمالا",
      'GU': "غوام",
      'GW': "غينيا بيساو",
      'GY': "غيانا",
      'HK': "هونغ كونغ الصينية (منطقة إدارية خاصة)",
      'HM': "جزيرة هيرد وجزر ماكدونالد",
      'HN': "هندوراس",
      'HR': "كرواتيا",
      'HT': "هايتي",
      'HU': "هنغاريا",
      'ID': "إندونيسيا",
      'IE': "أيرلندا",
      'IM': "جزيرة مان",
      'IN': "الهند",
      'IQ': "العراق",
      'IR': "إيران",
      'IS': "آيسلندا",
      'IT': "إيطاليا",
      'JE': "جيرسي",
      'JM': "جامايكا",
      'JO': "الأردن",
      'JP': "اليابان",
      'KE': "كينيا",
      'KG': "قيرغيزستان",
      'KH': "كمبوديا",
      'KI': "كيريباتي",
      'KM': "جزر القمر",
      'KN': "سانت كيتس ونيفيس",
      'KP': "كوريا الشمالية",
      'KR': "كوريا الجنوبية",
      'KW': "الكويت",
      'KY': "جزر كايمان",
      'KZ': "كازاخستان",
      'LA': "لاوس",
      'LB': "لبنان",
      'LC': "سانت لوسيا",
      'LI': "ليختنشتاين",
      'LK': "سريلانكا",
      'LR': "ليبيريا",
      'LS': "ليسوتو",
      'LT': "ليتوانيا",
      'LU': "لوكسمبورغ",
      'LV': "لاتفيا",
      'LY': "ليبيا",
      'MA': "المغرب",
      'MC': "موناكو",
      'MD': "مولدوفا",
      'ME': "الجبل الأسود",
      'MF': "سان مارتن",
      'MG': "مدغشقر",
      'MH': "جزر مارشال",
      'MK': "مقدونيا الشمالية",
      'ML': "مالي",
      'MM': "ميانمار (بورما)",
      'MN': "منغوليا",
      'MO': "منطقة ماكاو الإدارية الخاصة",
      'MP': "جزر ماريانا الشمالية",
      'MR': "موريتانيا",
      'MS': "مونتسرات",
      'MT': "مالطا",
      'MU': "موريشيوس",
      'MV': "جزر المالديف",
      'MW': "ملاوي",
      'MX': "المكسيك",
      'MY': "ماليزيا",
      'MZ': "موزمبيق",
      'NA': "ناميبيا",
      'NC': "كاليدونيا الجديدة",
      'NE': "النيجر",
      'NF': "جزيرة نورفولك",
      'NG': "نيجيريا",
      'NI': "نيكاراغوا",
      'NL': "هولندا",
      'NP': "نيبال",
      'NR': "ناورو",
      'NU': "نيوي",
      'NZ': "نيوزيلندا",
      'OM': "عُمان",
      'PA': "بنما",
      'PE': "بيرو",
      'PF': "بولينيزيا الفرنسية",
      'PG': "بابوا غينيا الجديدة",
      'PH': "الفلبين",
      'PK': "باكستان",
      'PL': "بولندا",
      'PM': "سان بيير ومكويلون",
      'PN': "جزر بيتكيرن",
      'PR': "بورتوريكو",
      'PT': "البرتغال",
      'PW': "بالاو",
      'PY': "باراغواي",
      'QA': "قطر",
      'RO': "رومانيا",
      'RS': "صربيا",
      'RU': "روسيا",
      'RW': "رواندا",
      'SA': "المملكة العربية السعودية",
      'SB': "جزر سليمان",
      'SC': "سيشل",
      'SD': "السودان",
      'SE': "السويد",
      'SG': "سنغافورة",
      'SH': "سانت هيلينا",
      'SI': "سلوفينيا",
      'SK': "سلوفاكيا",
      'SL': "سيراليون",
      'SM': "سان مارينو",
      'SN': "السنغال",
      'SO': "الصومال",
      'SR': "سورينام",
      'SS': "جنوب السودان",
      'ST': "ساو تومي وبرينسيبي",
      'SV': "السلفادور",
      'SX': "سانت مارتن",
      'SY': "سوريا",
      'SZ': "إسواتيني",
      'TC': "جزر توركس وكايكوس",
      'TD': "تشاد",
      'TF': "الأقاليم الجنوبية الفرنسية",
      'TG': "توغو",
      'TH': "تايلاند",
      'TJ': "طاجيكستان",
      'TL': "تيمور - ليشتي",
      'TM': "تركمانستان",
      'TN': "تونس",
      'TO': "تونغا",
      'TR': "تركيا",
      'TT': "ترينيداد وتوباغو",
      'TV': "توفالو",
      'TZ': "تنزانيا",
      'UA': "أوكرانيا",
      'UG': "أوغندا",
      'US': "الولايات المتحدة",
      'UY': "أورغواي",
      'UZ': "أوزبكستان",
      'VA': "الفاتيكان",
      'VC': "سانت فنسنت وجزر غرينادين",
      'VE': "فنزويلا",
      'VG': "جزر فيرجن البريطانية",
      'VI': "جزر فيرجن الأمريكية",
      'VN': "فيتنام",
      'VU': "فانواتو",
      'WF': "جزر والس وفوتونا",
      'WS': "ساموا",
      'YE': "اليمن",
      'ZA': "جنوب أفريقيا",
      'ZM': "زامبيا",
      'ZW': "زيمبابوي",
    },
    'bn': {
      'AD': "আন্ডোরা",
      'AE': "সংযুক্ত আরব আমিরাত",
      'AF': "আফগানিস্তান",
      'AG': "অ্যান্টিগুয়া ও বারবুডা",
      'AI': "অ্যাঙ্গুইলা",
      'AL': "আলবেনিয়া",
      'AM': "আর্মেনিয়া",
      'AO': "অ্যাঙ্গোলা",
      'AR': "আর্জেন্টিনা",
      'AS': "আমেরিকান সামোয়া",
      'AT': "অস্ট্রিয়া",
      'AU': "অস্ট্রেলিয়া",
      'AW': "আরুবা",
      'AX': "অলান্ড দ্বীপপুঞ্জ",
      'AZ': "আজারবাইজান",
      'BA': "বসনিয়া ও হার্জেগোভিনা",
      'BB': "বার্বাডোজ",
      'BD': "বাংলাদেশ",
      'BE': "বেলজিয়াম",
      'BF': "বুরকিনা ফাসো",
      'BG': "বুলগেরিয়া",
      'BH': "বাহারিন",
      'BI': "বুরুন্ডি",
      'BJ': "বেনিন",
      'BL': "সেন্ট বার্থেলেমি",
      'BM': "বারমুডা",
      'BN': "ব্রুনেই",
      'BO': "বলিভিয়া",
      'BR': "ব্রাজিল",
      'BS': "বাহামা দ্বীপপুঞ্জ",
      'BT': "ভুটান",
      'BW': "বতসোয়ানা",
      'BY': "বেলারুশ",
      'BZ': "বেলিজ",
      'CA': "কানাডা",
      'CD': "কঙ্গো-কিনশাসা",
      'CF': "মধ্য আফ্রিকার প্রজাতন্ত্র",
      'CG': "কঙ্গো - ব্রাজাভিল",
      'CH': "সুইজারল্যান্ড",
      'CI': "কোট ডি‘আইভোর",
      'CK': "কুক দ্বীপপুঞ্জ",
      'CL': "চিলি",
      'CM': "ক্যামেরুন",
      'CN': "চীন",
      'CO': "কলম্বিয়া",
      'CR': "কোস্টারিকা",
      'CU': "কিউবা",
      'CV': "কেপ ভার্দে",
      'CW': "কুরাসাও",
      'CY': "সাইপ্রাস",
      'CZ': "চেকিয়া",
      'DE': "জার্মানি",
      'DJ': "জিবুতি",
      'DK': "ডেনমার্ক",
      'DM': "ডোমিনিকা",
      'DO': "ডোমেনিকান প্রজাতন্ত্র",
      'DZ': "আলজেরিয়া",
      'EC': "ইকুয়েডর",
      'EE': "এস্তোনিয়া",
      'EG': "মিশর",
      'ER': "ইরিত্রিয়া",
      'ES': "স্পেন",
      'ET': "ইথিওপিয়া",
      'FI': "ফিনল্যান্ড",
      'FJ': "ফিজি",
      'FM': "মাইক্রোনেশিয়া",
      'FO': "ফ্যারো দ্বীপপুঞ্জ",
      'GA': "গ্যাবন",
      'GB': "যুক্তরাজ্য",
      'GD': "গ্রেনাডা",
      'GE': "জর্জিয়া",
      'GG': "গার্নসি",
      'GH': "ঘানা",
      'GL': "গ্রীনল্যান্ড",
      'GM': "গাম্বিয়া",
      'GN': "গিনি",
      'GQ': "নিরক্ষীয় গিনি",
      'GR': "গ্রীস",
      'GS': "দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ্জ",
      'GT': "গুয়াতেমালা",
      'GU': "গুয়াম",
      'GW': "গিনি-বিসাউ",
      'GY': "গিয়ানা",
      'HK': "হংকং এসএআর চীনা",
      'HM': "হার্ড এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ",
      'HN': "হন্ডুরাস",
      'HR': "ক্রোয়েশিয়া",
      'HT': "হাইতি",
      'HU': "হাঙ্গেরি",
      'ID': "ইন্দোনেশিয়া",
      'IE': "আয়ারল্যান্ড",
      'IM': "আইল অফ ম্যান",
      'IN': "ভারত",
      'IQ': "ইরাক",
      'IR': "ইরান",
      'IS': "আইসল্যান্ড",
      'IT': "ইতালি",
      'JE': "জার্সি",
      'JM': "জামাইকা",
      'JO': "জর্ডন",
      'JP': "জাপান",
      'KE': "কেনিয়া",
      'KG': "কিরগিজিস্তান",
      'KH': "কম্বোডিয়া",
      'KI': "কিরিবাতি",
      'KM': "কমোরোস",
      'KN': "সেন্ট কিটস ও নেভিস",
      'KP': "উত্তর কোরিয়া",
      'KR': "দক্ষিণ কোরিয়া",
      'KW': "কুয়েত",
      'KY': "কেম্যান দ্বীপপুঞ্জ",
      'KZ': "কাজাখস্তান",
      'LA': "লাওস",
      'LB': "লেবানন",
      'LC': "সেন্ট লুসিয়া",
      'LI': "লিচেনস্টেইন",
      'LK': "শ্রীলঙ্কা",
      'LR': "লাইবেরিয়া",
      'LS': "লেসোথো",
      'LT': "লিথুয়ানিয়া",
      'LU': "লাক্সেমবার্গ",
      'LV': "লাটভিয়া",
      'LY': "লিবিয়া",
      'MA': "মোরক্কো",
      'MC': "মোনাকো",
      'MD': "মলডোভা",
      'ME': "মন্টিনিগ্রো",
      'MF': "সেন্ট মার্টিন",
      'MG': "মাদাগাস্কার",
      'MH': "মার্শাল দ্বীপপুঞ্জ",
      'MK': "উত্তর ম্যাসেডোনিয়া",
      'ML': "মালি",
      'MM': "মায়ানমার (বার্মা)",
      'MN': "মঙ্গোলিয়া",
      'MO': "ম্যাকাও এসএআর চীন",
      'MP': "উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ",
      'MR': "মরিতানিয়া",
      'MS': "মন্টসেরাট",
      'MT': "মাল্টা",
      'MU': "মরিশাস",
      'MV': "মালদ্বীপ",
      'MW': "মালাউই",
      'MX': "মেক্সিকো",
      'MY': "মালয়েশিয়া",
      'MZ': "মোজাম্বিক",
      'NA': "নামিবিয়া",
      'NC': "নিউ ক্যালেডোনিয়া",
      'NE': "নাইজার",
      'NF': "নরফোক দ্বীপ",
      'NG': "নাইজেরিয়া",
      'NI': "নিকারাগুয়া",
      'NL': "নেদারল্যান্ডস",
      'NP': "নেপাল",
      'NR': "নাউরু",
      'NU': "নিউয়ে",
      'NZ': "নিউজিল্যান্ড",
      'OM': "ওমান",
      'PA': "পানামা",
      'PE': "পেরু",
      'PF': "ফরাসী পলিনেশিয়া",
      'PG': "পাপুয়া নিউ গিনি",
      'PH': "ফিলিপাইন",
      'PK': "পাকিস্তান",
      'PL': "পোল্যান্ড",
      'PM': "সেন্ট পিয়ের ও মিকুয়েলন",
      'PN': "পিটকেয়ার্ন দ্বীপপুঞ্জ",
      'PR': "পুয়ের্তো রিকো",
      'PT': "পর্তুগাল",
      'PW': "পালাউ",
      'PY': "প্যারাগুয়ে",
      'QA': "কাতার",
      'RO': "রোমানিয়া",
      'RS': "সার্বিয়া",
      'RU': "রাশিয়া",
      'RW': "রুয়ান্ডা",
      'SA': "সৌদি আরব",
      'SB': "সলোমন দ্বীপপুঞ্জ",
      'SC': "সিসিলি",
      'SD': "সুদান",
      'SE': "সুইডেন",
      'SG': "সিঙ্গাপুর",
      'SH': "সেন্ট হেলেনা",
      'SI': "স্লোভানিয়া",
      'SK': "স্লোভাকিয়া",
      'SL': "সিয়েরা লিওন",
      'SM': "সান মারিনো",
      'SN': "সেনেগাল",
      'SO': "সোমালিয়া",
      'SR': "সুরিনাম",
      'SS': "দক্ষিণ সুদান",
      'ST': "সাওটোমা ও প্রিন্সিপি",
      'SV': "এল সালভেদর",
      'SX': "সিন্ট মার্টেন",
      'SY': "সিরিয়া",
      'SZ': "ইসওয়াতিনি",
      'TC': "তুর্কস ও কাইকোস দ্বীপপুঞ্জ",
      'TD': "চাদ",
      'TF': "ফরাসী দক্ষিণাঞ্চল",
      'TG': "টোগো",
      'TH': "থাইল্যান্ড",
      'TJ': "তাজিকিস্তান",
      'TL': "তিমুর-লেস্তে",
      'TM': "তুর্কমেনিস্তান",
      'TN': "তিউনিসিয়া",
      'TO': "টোঙ্গা",
      'TR': "তুরস্ক",
      'TT': "ত্রিনিনাদ ও টোব্যাগো",
      'TV': "টুভালু",
      'TZ': "তাঞ্জানিয়া",
      'UA': "ইউক্রেন",
      'UG': "উগান্ডা",
      'US': "মার্কিন যুক্তরাষ্ট্র",
      'UY': "উরুগুয়ে",
      'UZ': "উজবেকিস্তান",
      'VA': "ভ্যাটিকান সিটি",
      'VC': "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস",
      'VE': "ভেনেজুয়েলা",
      'VG': "ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ",
      'VI': "মার্কিন যুক্তরাষ্ট্রীয় ভার্জিন দ্বীপপুঞ্জ",
      'VN': "ভিয়েতনাম",
      'VU': "ভানুয়াটু",
      'WF': "ওয়ালিস ও ফুটুনা",
      'WS': "সামোয়া",
      'YE': "ইয়েমেন",
      'ZA': "দক্ষিণ আফ্রিকা",
      'ZM': "জাম্বিয়া",
      'ZW': "জিম্বাবোয়ে",
    },
    'de': {
      'AD': "Andorra",
      'AE': "Vereinigte Arabische Emirate",
      'AF': "Afghanistan",
      'AG': "Antigua und Barbuda",
      'AI': "Anguilla",
      'AL': "Albanien",
      'AM': "Armenien",
      'AO': "Angola",
      'AR': "Argentinien",
      'AS': "Amerikanisch-Samoa",
      'AT': "Österreich",
      'AU': "Australien",
      'AW': "Aruba",
      'AX': "Ålandinseln",
      'AZ': "Aserbaidschan",
      'BA': "Bosnien und Herzegowina",
      'BB': "Barbados",
      'BD': "Bangladesch",
      'BE': "Belgien",
      'BF': "Burkina Faso",
      'BG': "Bulgarien",
      'BH': "Bahrain",
      'BI': "Burundi",
      'BJ': "Benin",
      'BL': "St. Barthélemy",
      'BM': "Bermuda",
      'BN': "Brunei Darussalam",
      'BO': "Bolivien",
      'BR': "Brasilien",
      'BS': "Bahamas",
      'BT': "Bhutan",
      'BW': "Botsuana",
      'BY': "Belarus",
      'BZ': "Belize",
      'CA': "Kanada",
      'CD': "Kongo-Kinshasa",
      'CF': "Zentralafrikanische Republik",
      'CG': "Kongo-Brazzaville",
      'CH': "Schweiz",
      'CI': "Côte d’Ivoire",
      'CK': "Cookinseln",
      'CL': "Chile",
      'CM': "Kamerun",
      'CN': "China",
      'CO': "Kolumbien",
      'CR': "Costa Rica",
      'CU': "Kuba",
      'CV': "Cabo Verde",
      'CW': "Curaçao",
      'CY': "Zypern",
      'CZ': "Tschechien",
      'DE': "Deutschland",
      'DJ': "Dschibuti",
      'DK': "Dänemark",
      'DM': "Dominica",
      'DO': "Dominikanische Republik",
      'DZ': "Algerien",
      'EC': "Ecuador",
      'EE': "Estland",
      'EG': "Ägypten",
      'ER': "Eritrea",
      'ES': "Spanien",
      'ET': "Äthiopien",
      'FI': "Finnland",
      'FJ': "Fidschi",
      'FM': "Mikronesien",
      'FO': "Färöer",
      'GA': "Gabun",
      'GB': "Vereinigtes Königreich",
      'GD': "Grenada",
      'GE': "Georgien",
      'GG': "Guernsey",
      'GH': "Ghana",
      'GL': "Grönland",
      'GM': "Gambia",
      'GN': "Guinea",
      'GQ': "Äquatorialguinea",
      'GR': "Griechenland",
      'GS': "Südgeorgien und die Südlichen Sandwichinseln",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Guinea-Bissau",
      'GY': "Guyana",
      'HK': "Sonderverwaltungsregion Hongkong",
      'HM': "Heard und McDonaldinseln",
      'HN': "Honduras",
      'HR': "Kroatien",
      'HT': "Haiti",
      'HU': "Ungarn",
      'ID': "Indonesien",
      'IE': "Irland",
      'IM': "Isle of Man",
      'IN': "Indien",
      'IQ': "Irak",
      'IR': "Iran",
      'IS': "Island",
      'IT': "Italien",
      'JE': "Jersey",
      'JM': "Jamaika",
      'JO': "Jordanien",
      'JP': "Japan",
      'KE': "Kenia",
      'KG': "Kirgisistan",
      'KH': "Kambodscha",
      'KI': "Kiribati",
      'KM': "Komoren",
      'KN': "St. Kitts und Nevis",
      'KP': "Nordkorea",
      'KR': "Südkorea",
      'KW': "Kuwait",
      'KY': "Kaimaninseln",
      'KZ': "Kasachstan",
      'LA': "Laos",
      'LB': "Libanon",
      'LC': "St. Lucia",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberia",
      'LS': "Lesotho",
      'LT': "Litauen",
      'LU': "Luxemburg",
      'LV': "Lettland",
      'LY': "Libyen",
      'MA': "Marokko",
      'MC': "Monaco",
      'MD': "Republik Moldau",
      'ME': "Montenegro",
      'MF': "St. Martin",
      'MG': "Madagaskar",
      'MH': "Marshallinseln",
      'MK': "Nordmazedonien",
      'ML': "Mali",
      'MM': "Myanmar",
      'MN': "Mongolei",
      'MO': "Sonderverwaltungsregion Macau",
      'MP': "Nördliche Marianen",
      'MR': "Mauretanien",
      'MS': "Montserrat",
      'MT': "Malta",
      'MU': "Mauritius",
      'MV': "Malediven",
      'MW': "Malawi",
      'MX': "Mexiko",
      'MY': "Malaysia",
      'MZ': "Mosambik",
      'NA': "Namibia",
      'NC': "Neukaledonien",
      'NE': "Niger",
      'NF': "Norfolkinsel",
      'NG': "Nigeria",
      'NI': "Nicaragua",
      'NL': "Niederlande",
      'NP': "Nepal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "Neuseeland",
      'OM': "Oman",
      'PA': "Panama",
      'PE': "Peru",
      'PF': "Französisch-Polynesien",
      'PG': "Papua-Neuguinea",
      'PH': "Philippinen",
      'PK': "Pakistan",
      'PL': "Polen",
      'PM': "St. Pierre und Miquelon",
      'PN': "Pitcairninseln",
      'PR': "Puerto Rico",
      'PT': "Portugal",
      'PW': "Palau",
      'PY': "Paraguay",
      'QA': "Katar",
      'RO': "Rumänien",
      'RS': "Serbien",
      'RU': "Russland",
      'RW': "Ruanda",
      'SA': "Saudi-Arabien",
      'SB': "Salomonen",
      'SC': "Seychellen",
      'SD': "Sudan",
      'SE': "Schweden",
      'SG': "Singapur",
      'SH': "St. Helena",
      'SI': "Slowenien",
      'SK': "Slowakei",
      'SL': "Sierra Leone",
      'SM': "San Marino",
      'SN': "Senegal",
      'SO': "Somalia",
      'SR': "Suriname",
      'SS': "Südsudan",
      'ST': "São Tomé und Príncipe",
      'SV': "El Salvador",
      'SX': "Sint Maarten",
      'SY': "Syrien",
      'SZ': "Eswatini",
      'TC': "Turks- und Caicosinseln",
      'TD': "Tschad",
      'TF': "Französische Süd- und Antarktisgebiete",
      'TG': "Togo",
      'TH': "Thailand",
      'TJ': "Tadschikistan",
      'TL': "Timor-Leste",
      'TM': "Turkmenistan",
      'TN': "Tunesien",
      'TO': "Tonga",
      'TR': "Türkei",
      'TT': "Trinidad und Tobago",
      'TV': "Tuvalu",
      'TZ': "Tansania",
      'UA': "Ukraine",
      'UG': "Uganda",
      'US': "Vereinigte Staaten",
      'UY': "Uruguay",
      'UZ': "Usbekistan",
      'VA': "Vatikanstadt",
      'VC': "St. Vincent und die Grenadinen",
      'VE': "Venezuela",
      'VG': "Britische Jungferninseln",
      'VI': "Amerikanische Jungferninseln",
      'VN': "Vietnam",
      'VU': "Vanuatu",
      'WF': "Wallis und Futuna",
      'WS': "Samoa",
      'YE': "Jemen",
      'ZA': "Südafrika",
      'ZM': "Sambia",
      'ZW': "Simbabwe",
    },
    'en': {
      'AD': "Andorra",
      'AE': "United Arab Emirates",
      'AF': "Afghanistan",
      'AG': "Antigua & Barbuda",
      'AI': "Anguilla",
      'AL': "Albania",
      'AM': "Armenia",
      'AO': "Angola",
      'AR': "Argentina",
      'AS': "American Samoa",
      'AT': "Austria",
      'AU': "Australia",
      'AW': "Aruba",
      'AX': "Åland Islands",
      'AZ': "Azerbaijan",
      'BA': "Bosnia & Herzegovina",
      'BB': "Barbados",
      'BD': "Bangladesh",
      'BE': "Belgium",
      'BF': "Burkina Faso",
      'BG': "Bulgaria",
      'BH': "Bahrain",
      'BI': "Burundi",
      'BJ': "Benin",
      'BL': "St. Barthélemy",
      'BM': "Bermuda",
      'BN': "Brunei",
      'BO': "Bolivia",
      'BR': "Brazil",
      'BS': "Bahamas",
      'BT': "Bhutan",
      'BW': "Botswana",
      'BY': "Belarus",
      'BZ': "Belize",
      'CA': "Canada",
      'CD': "Congo - Kinshasa",
      'CF': "Central African Republic",
      'CG': "Congo - Brazzaville",
      'CH': "Switzerland",
      'CI': "Côte d’Ivoire",
      'CK': "Cook Islands",
      'CL': "Chile",
      'CM': "Cameroon",
      'CN': "China",
      'CO': "Colombia",
      'CR': "Costa Rica",
      'CU': "Cuba",
      'CV': "Cape Verde",
      'CW': "Curaçao",
      'CY': "Cyprus",
      'CZ': "Czechia",
      'DE': "Germany",
      'DJ': "Djibouti",
      'DK': "Denmark",
      'DM': "Dominica",
      'DO': "Dominican Republic",
      'DZ': "Algeria",
      'EC': "Ecuador",
      'EE': "Estonia",
      'EG': "Egypt",
      'ER': "Eritrea",
      'ES': "Spain",
      'ET': "Ethiopia",
      'FI': "Finland",
      'FJ': "Fiji",
      'FM': "Micronesia",
      'FO': "Faroe Islands",
      'GA': "Gabon",
      'GB': "United Kingdom",
      'GD': "Grenada",
      'GE': "Georgia",
      'GG': "Guernsey",
      'GH': "Ghana",
      'GL': "Greenland",
      'GM': "Gambia",
      'GN': "Guinea",
      'GQ': "Equatorial Guinea",
      'GR': "Greece",
      'GS': "South Georgia & South Sandwich Islands",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Guinea-Bissau",
      'GY': "Guyana",
      'HK': "Hong Kong SAR China",
      'HM': "Heard & McDonald Islands",
      'HN': "Honduras",
      'HR': "Croatia",
      'HT': "Haiti",
      'HU': "Hungary",
      'ID': "Indonesia",
      'IE': "Ireland",
      'IM': "Isle of Man",
      'IN': "India",
      'IQ': "Iraq",
      'IR': "Iran",
      'IS': "Iceland",
      'IT': "Italy",
      'JE': "Jersey",
      'JM': "Jamaica",
      'JO': "Jordan",
      'JP': "Japan",
      'KE': "Kenya",
      'KG': "Kyrgyzstan",
      'KH': "Cambodia",
      'KI': "Kiribati",
      'KM': "Comoros",
      'KN': "St. Kitts & Nevis",
      'KP': "North Korea",
      'KR': "South Korea",
      'KW': "Kuwait",
      'KY': "Cayman Islands",
      'KZ': "Kazakhstan",
      'LA': "Laos",
      'LB': "Lebanon",
      'LC': "St. Lucia",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberia",
      'LS': "Lesotho",
      'LT': "Lithuania",
      'LU': "Luxembourg",
      'LV': "Latvia",
      'LY': "Libya",
      'MA': "Morocco",
      'MC': "Monaco",
      'MD': "Moldova",
      'ME': "Montenegro",
      'MF': "St. Martin",
      'MG': "Madagascar",
      'MH': "Marshall Islands",
      'MK': "North Macedonia",
      'ML': "Mali",
      'MM': "Myanmar (Burma)",
      'MN': "Mongolia",
      'MO': "Macao SAR China",
      'MP': "Northern Mariana Islands",
      'MR': "Mauritania",
      'MS': "Montserrat",
      'MT': "Malta",
      'MU': "Mauritius",
      'MV': "Maldives",
      'MW': "Malawi",
      'MX': "Mexico",
      'MY': "Malaysia",
      'MZ': "Mozambique",
      'NA': "Namibia",
      'NC': "New Caledonia",
      'NE': "Niger",
      'NF': "Norfolk Island",
      'NG': "Nigeria",
      'NI': "Nicaragua",
      'NL': "Netherlands",
      'NP': "Nepal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "New Zealand",
      'OM': "Oman",
      'PA': "Panama",
      'PE': "Peru",
      'PF': "French Polynesia",
      'PG': "Papua New Guinea",
      'PH': "Philippines",
      'PK': "Pakistan",
      'PL': "Poland",
      'PM': "St. Pierre & Miquelon",
      'PN': "Pitcairn Islands",
      'PR': "Puerto Rico",
      'PT': "Portugal",
      'PW': "Palau",
      'PY': "Paraguay",
      'QA': "Qatar",
      'RO': "Romania",
      'RS': "Serbia",
      'RU': "Russia",
      'RW': "Rwanda",
      'SA': "Saudi Arabia",
      'SB': "Solomon Islands",
      'SC': "Seychelles",
      'SD': "Sudan",
      'SE': "Sweden",
      'SG': "Singapore",
      'SH': "St. Helena",
      'SI': "Slovenia",
      'SK': "Slovakia",
      'SL': "Sierra Leone",
      'SM': "San Marino",
      'SN': "Senegal",
      'SO': "Somalia",
      'SR': "Suriname",
      'SS': "South Sudan",
      'ST': "São Tomé & Príncipe",
      'SV': "El Salvador",
      'SX': "Sint Maarten",
      'SY': "Syria",
      'SZ': "Eswatini",
      'TC': "Turks & Caicos Islands",
      'TD': "Chad",
      'TF': "French Southern Territories",
      'TG': "Togo",
      'TH': "Thailand",
      'TJ': "Tajikistan",
      'TL': "Timor-Leste",
      'TM': "Turkmenistan",
      'TN': "Tunisia",
      'TO': "Tonga",
      'TR': "Türkiye",
      'TT': "Trinidad & Tobago",
      'TV': "Tuvalu",
      'TZ': "Tanzania",
      'UA': "Ukraine",
      'UG': "Uganda",
      'US': "United States",
      'UY': "Uruguay",
      'UZ': "Uzbekistan",
      'VA': "Vatican City",
      'VC': "St. Vincent & Grenadines",
      'VE': "Venezuela",
      'VG': "British Virgin Islands",
      'VI': "U.S. Virgin Islands",
      'VN': "Vietnam",
      'VU': "Vanuatu",
      'WF': "Wallis & Futuna",
      'WS': "Samoa",
      'YE': "Yemen",
      'ZA': "South Africa",
      'ZM': "Zambia",
      'ZW': "Zimbabwe",
    },
    'es': {
      'AD': "Andorra",
      'AE': "Emiratos Árabes Unidos",
      'AF': "Afganistán",
      'AG': "Antigua y Barbuda",
      'AI': "Anguila",
      'AL': "Albania",
      'AM': "Armenia",
      'AO': "Angola",
      'AR': "Argentina",
      'AS': "Samoa Americana",
      'AT': "Austria",
      'AU': "Australia",
      'AW': "Aruba",
      'AX': "Islas Aland",
      'AZ': "Azerbaiyán",
      'BA': "Bosnia y Herzegovina",
      'BB': "Barbados",
      'BD': "Bangladés",
      'BE': "Bélgica",
      'BF': "Burkina Faso",
      'BG': "Bulgaria",
      'BH': "Baréin",
      'BI': "Burundi",
      'BJ': "Benín",
      'BL': "San Bartolomé",
      'BM': "Bermudas",
      'BN': "Brunéi",
      'BO': "Bolivia",
      'BR': "Brasil",
      'BS': "Bahamas",
      'BT': "Bután",
      'BW': "Botsuana",
      'BY': "Bielorrusia",
      'BZ': "Belice",
      'CA': "Canadá",
      'CD': "República Democrática del Congo",
      'CF': "República Centroafricana",
      'CG': "Congo",
      'CH': "Suiza",
      'CI': "Côte d’Ivoire",
      'CK': "Islas Cook",
      'CL': "Chile",
      'CM': "Camerún",
      'CN': "China",
      'CO': "Colombia",
      'CR': "Costa Rica",
      'CU': "Cuba",
      'CV': "Cabo Verde",
      'CW': "Curazao",
      'CY': "Chipre",
      'CZ': "Chequia",
      'DE': "Alemania",
      'DJ': "Yibuti",
      'DK': "Dinamarca",
      'DM': "Dominica",
      'DO': "República Dominicana",
      'DZ': "Argelia",
      'EC': "Ecuador",
      'EE': "Estonia",
      'EG': "Egipto",
      'ER': "Eritrea",
      'ES': "España",
      'ET': "Etiopía",
      'FI': "Finlandia",
      'FJ': "Fiyi",
      'FM': "Micronesia",
      'FO': "Islas Feroe",
      'GA': "Gabón",
      'GB': "Reino Unido",
      'GD': "Granada",
      'GE': "Georgia",
      'GG': "Guernesey",
      'GH': "Ghana",
      'GL': "Groenlandia",
      'GM': "Gambia",
      'GN': "Guinea",
      'GQ': "Guinea Ecuatorial",
      'GR': "Grecia",
      'GS': "Islas Georgia del Sur y Sandwich del Sur",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Guinea-Bisáu",
      'GY': "Guyana",
      'HK': "RAE de Hong Kong (China)",
      'HM': "Islas Heard y McDonald",
      'HN': "Honduras",
      'HR': "Croacia",
      'HT': "Haití",
      'HU': "Hungría",
      'ID': "Indonesia",
      'IE': "Irlanda",
      'IM': "Isla de Man",
      'IN': "India",
      'IQ': "Irak",
      'IR': "Irán",
      'IS': "Islandia",
      'IT': "Italia",
      'JE': "Jersey",
      'JM': "Jamaica",
      'JO': "Jordania",
      'JP': "Japón",
      'KE': "Kenia",
      'KG': "Kirguistán",
      'KH': "Camboya",
      'KI': "Kiribati",
      'KM': "Comoras",
      'KN': "San Cristóbal y Nieves",
      'KP': "Corea del Norte",
      'KR': "Corea del Sur",
      'KW': "Kuwait",
      'KY': "Islas Caimán",
      'KZ': "Kazajistán",
      'LA': "Laos",
      'LB': "Líbano",
      'LC': "Santa Lucía",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberia",
      'LS': "Lesoto",
      'LT': "Lituania",
      'LU': "Luxemburgo",
      'LV': "Letonia",
      'LY': "Libia",
      'MA': "Marruecos",
      'MC': "Mónaco",
      'MD': "Moldavia",
      'ME': "Montenegro",
      'MF': "San Martín",
      'MG': "Madagascar",
      'MH': "Islas Marshall",
      'MK': "Macedonia del Norte",
      'ML': "Mali",
      'MM': "Myanmar (Birmania)",
      'MN': "Mongolia",
      'MO': "RAE de Macao (China)",
      'MP': "Islas Marianas del Norte",
      'MR': "Mauritania",
      'MS': "Montserrat",
      'MT': "Malta",
      'MU': "Mauricio",
      'MV': "Maldivas",
      'MW': "Malaui",
      'MX': "México",
      'MY': "Malasia",
      'MZ': "Mozambique",
      'NA': "Namibia",
      'NC': "Nueva Caledonia",
      'NE': "Níger",
      'NF': "Isla Norfolk",
      'NG': "Nigeria",
      'NI': "Nicaragua",
      'NL': "Países Bajos",
      'NP': "Nepal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "Nueva Zelanda",
      'OM': "Omán",
      'PA': "Panamá",
      'PE': "Perú",
      'PF': "Polinesia Francesa",
      'PG': "Papúa Nueva Guinea",
      'PH': "Filipinas",
      'PK': "Pakistán",
      'PL': "Polonia",
      'PM': "San Pedro y Miquelón",
      'PN': "Islas Pitcairn",
      'PR': "Puerto Rico",
      'PT': "Portugal",
      'PW': "Palaos",
      'PY': "Paraguay",
      'QA': "Catar",
      'RO': "Rumanía",
      'RS': "Serbia",
      'RU': "Rusia",
      'RW': "Ruanda",
      'SA': "Arabia Saudí",
      'SB': "Islas Salomón",
      'SC': "Seychelles",
      'SD': "Sudán",
      'SE': "Suecia",
      'SG': "Singapur",
      'SH': "Santa Elena",
      'SI': "Eslovenia",
      'SK': "Eslovaquia",
      'SL': "Sierra Leona",
      'SM': "San Marino",
      'SN': "Senegal",
      'SO': "Somalia",
      'SR': "Surinam",
      'SS': "Sudán del Sur",
      'ST': "Santo Tomé y Príncipe",
      'SV': "El Salvador",
      'SX': "Sint Maarten",
      'SY': "Siria",
      'SZ': "Esuatini",
      'TC': "Islas Turcas y Caicos",
      'TD': "Chad",
      'TF': "Territorios Australes Franceses",
      'TG': "Togo",
      'TH': "Tailandia",
      'TJ': "Tayikistán",
      'TL': "Timor-Leste",
      'TM': "Turkmenistán",
      'TN': "Túnez",
      'TO': "Tonga",
      'TR': "Turquía",
      'TT': "Trinidad y Tobago",
      'TV': "Tuvalu",
      'TZ': "Tanzania",
      'UA': "Ucrania",
      'UG': "Uganda",
      'US': "Estados Unidos",
      'UY': "Uruguay",
      'UZ': "Uzbekistán",
      'VA': "Ciudad del Vaticano",
      'VC': "San Vicente y las Granadinas",
      'VE': "Venezuela",
      'VG': "Islas Vírgenes Británicas",
      'VI': "Islas Vírgenes de EE. UU.",
      'VN': "Vietnam",
      'VU': "Vanuatu",
      'WF': "Wallis y Futuna",
      'WS': "Samoa",
      'YE': "Yemen",
      'ZA': "Sudáfrica",
      'ZM': "Zambia",
      'ZW': "Zimbabue",
    },
    'fr': {
      'AD': "Andorre",
      'AE': "Émirats arabes unis",
      'AF': "Afghanistan",
      'AG': "Antigua-et-Barbuda",
      'AI': "Anguilla",
      'AL': "Albanie",
      'AM': "Arménie",
      'AO': "Angola",
      'AR': "Argentine",
      'AS': "Samoa américaines",
      'AT': "Autriche",
      'AU': "Australie",
      'AW': "Aruba",
      'AX': "Îles Åland",
      'AZ': "Azerbaïdjan",
      'BA': "Bosnie-Herzégovine",
      'BB': "Barbade",
      'BD': "Bangladesh",
      'BE': "Belgique",
      'BF': "Burkina Faso",
      'BG': "Bulgarie",
      'BH': "Bahreïn",
      'BI': "Burundi",
      'BJ': "Bénin",
      'BL': "Saint-Barthélemy",
      'BM': "Bermudes",
      'BN': "Brunei",
      'BO': "Bolivie",
      'BR': "Brésil",
      'BS': "Bahamas",
      'BT': "Bhoutan",
      'BW': "Botswana",
      'BY': "Biélorussie",
      'BZ': "Belize",
      'CA': "Canada",
      'CD': "Congo-Kinshasa",
      'CF': "République centrafricaine",
      'CG': "Congo-Brazzaville",
      'CH': "Suisse",
      'CI': "Côte d’Ivoire",
      'CK': "Îles Cook",
      'CL': "Chili",
      'CM': "Cameroun",
      'CN': "Chine",
      'CO': "Colombie",
      'CR': "Costa Rica",
      'CU': "Cuba",
      'CV': "Cap-Vert",
      'CW': "Curaçao",
      'CY': "Chypre",
      'CZ': "Tchéquie",
      'DE': "Allemagne",
      'DJ': "Djibouti",
      'DK': "Danemark",
      'DM': "Dominique",
      'DO': "République dominicaine",
      'DZ': "Algérie",
      'EC': "Équateur",
      'EE': "Estonie",
      'EG': "Égypte",
      'ER': "Érythrée",
      'ES': "Espagne",
      'ET': "Éthiopie",
      'FI': "Finlande",
      'FJ': "Fidji",
      'FM': "Micronésie",
      'FO': "Îles Féroé",
      'GA': "Gabon",
      'GB': "Royaume-Uni",
      'GD': "Grenade",
      'GE': "Géorgie",
      'GG': "Guernesey",
      'GH': "Ghana",
      'GL': "Groenland",
      'GM': "Gambie",
      'GN': "Guinée",
      'GQ': "Guinée équatoriale",
      'GR': "Grèce",
      'GS': "Géorgie du Sud-et-les Îles Sandwich du Sud",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Guinée-Bissau",
      'GY': "Guyana",
      'HK': "R.A.S. chinoise de Hong Kong",
      'HM': "Îles Heard-et-MacDonald",
      'HN': "Honduras",
      'HR': "Croatie",
      'HT': "Haïti",
      'HU': "Hongrie",
      'ID': "Indonésie",
      'IE': "Irlande",
      'IM': "Île de Man",
      'IN': "Inde",
      'IQ': "Irak",
      'IR': "Iran",
      'IS': "Islande",
      'IT': "Italie",
      'JE': "Jersey",
      'JM': "Jamaïque",
      'JO': "Jordanie",
      'JP': "Japon",
      'KE': "Kenya",
      'KG': "Kirghizstan",
      'KH': "Cambodge",
      'KI': "Kiribati",
      'KM': "Comores",
      'KN': "Saint-Christophe-et-Niévès",
      'KP': "Corée du Nord",
      'KR': "Corée du Sud",
      'KW': "Koweït",
      'KY': "Îles Caïmans",
      'KZ': "Kazakhstan",
      'LA': "Laos",
      'LB': "Liban",
      'LC': "Sainte-Lucie",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberia",
      'LS': "Lesotho",
      'LT': "Lituanie",
      'LU': "Luxembourg",
      'LV': "Lettonie",
      'LY': "Libye",
      'MA': "Maroc",
      'MC': "Monaco",
      'MD': "Moldavie",
      'ME': "Monténégro",
      'MF': "Saint-Martin",
      'MG': "Madagascar",
      'MH': "Îles Marshall",
      'MK': "Macédoine du Nord",
      'ML': "Mali",
      'MM': "Myanmar (Birmanie)",
      'MN': "Mongolie",
      'MO': "R.A.S. chinoise de Macao",
      'MP': "Îles Mariannes du Nord",
      'MR': "Mauritanie",
      'MS': "Montserrat",
      'MT': "Malte",
      'MU': "Maurice",
      'MV': "Maldives",
      'MW': "Malawi",
      'MX': "Mexique",
      'MY': "Malaisie",
      'MZ': "Mozambique",
      'NA': "Namibie",
      'NC': "Nouvelle-Calédonie",
      'NE': "Niger",
      'NF': "Île Norfolk",
      'NG': "Nigeria",
      'NI': "Nicaragua",
      'NL': "Pays-Bas",
      'NP': "Népal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "Nouvelle-Zélande",
      'OM': "Oman",
      'PA': "Panama",
      'PE': "Pérou",
      'PF': "Polynésie française",
      'PG': "Papouasie-Nouvelle-Guinée",
      'PH': "Philippines",
      'PK': "Pakistan",
      'PL': "Pologne",
      'PM': "Saint-Pierre-et-Miquelon",
      'PN': "Îles Pitcairn",
      'PR': "Porto Rico",
      'PT': "Portugal",
      'PW': "Palaos",
      'PY': "Paraguay",
      'QA': "Qatar",
      'RO': "Roumanie",
      'RS': "Serbie",
      'RU': "Russie",
      'RW': "Rwanda",
      'SA': "Arabie saoudite",
      'SB': "Îles Salomon",
      'SC': "Seychelles",
      'SD': "Soudan",
      'SE': "Suède",
      'SG': "Singapour",
      'SH': "Sainte-Hélène",
      'SI': "Slovénie",
      'SK': "Slovaquie",
      'SL': "Sierra Leone",
      'SM': "Saint-Marin",
      'SN': "Sénégal",
      'SO': "Somalie",
      'SR': "Suriname",
      'SS': "Soudan du Sud",
      'ST': "Sao Tomé-et-Principe",
      'SV': "Salvador",
      'SX': "Saint-Martin (partie néerlandaise)",
      'SY': "Syrie",
      'SZ': "Eswatini",
      'TC': "Îles Turques-et-Caïques",
      'TD': "Tchad",
      'TF': "Terres australes françaises",
      'TG': "Togo",
      'TH': "Thaïlande",
      'TJ': "Tadjikistan",
      'TL': "Timor oriental",
      'TM': "Turkménistan",
      'TN': "Tunisie",
      'TO': "Tonga",
      'TR': "Turquie",
      'TT': "Trinité-et-Tobago",
      'TV': "Tuvalu",
      'TZ': "Tanzanie",
      'UA': "Ukraine",
      'UG': "Ouganda",
      'US': "États-Unis",
      'UY': "Uruguay",
      'UZ': "Ouzbékistan",
      'VA': "État de la Cité du Vatican",
      'VC': "Saint-Vincent-et-les Grenadines",
      'VE': "Venezuela",
      'VG': "Îles Vierges britanniques",
      'VI': "Îles Vierges des États-Unis",
      'VN': "Viêt Nam",
      'VU': "Vanuatu",
      'WF': "Wallis-et-Futuna",
      'WS': "Samoa",
      'YE': "Yémen",
      'ZA': "Afrique du Sud",
      'ZM': "Zambie",
      'ZW': "Zimbabwe",
    },
    'ms': {
      'AD': "Andorra",
      'AE': "Emiriah Arab Bersatu",
      'AF': "Afghanistan",
      'AG': "Antigua dan Barbuda",
      'AI': "Anguilla",
      'AL': "Albania",
      'AM': "Armenia",
      'AO': "Angola",
      'AR': "Argentina",
      'AS': "Samoa Amerika",
      'AT': "Austria",
      'AU': "Australia",
      'AW': "Aruba",
      'AX': "Kepulauan Aland",
      'AZ': "Azerbaijan",
      'BA': "Bosnia dan Herzegovina",
      'BB': "Barbados",
      'BD': "Bangladesh",
      'BE': "Belgium",
      'BF': "Burkina Faso",
      'BG': "Bulgaria",
      'BH': "Bahrain",
      'BI': "Burundi",
      'BJ': "Benin",
      'BL': "St. Barthelemy",
      'BM': "Bermuda",
      'BN': "Brunei",
      'BO': "Bolivia",
      'BR': "Brazil",
      'BS': "Bahamas",
      'BT': "Bhutan",
      'BW': "Botswana",
      'BY': "Belarus",
      'BZ': "Belize",
      'CA': "Kanada",
      'CD': "Congo - Kinshasa",
      'CF': "Republik Afrika Tengah",
      'CG': "Congo - Brazzaville",
      'CH': "Switzerland",
      'CI': "Cote d’Ivoire",
      'CK': "Kepulauan Cook",
      'CL': "Chile",
      'CM': "Cameroon",
      'CN': "China",
      'CO': "Colombia",
      'CR': "Costa Rica",
      'CU': "Cuba",
      'CV': "Cape Verde",
      'CW': "Curacao",
      'CY': "Cyprus",
      'CZ': "Czechia",
      'DE': "Jerman",
      'DJ': "Djibouti",
      'DK': "Denmark",
      'DM': "Dominica",
      'DO': "Republik Dominica",
      'DZ': "Algeria",
      'EC': "Ecuador",
      'EE': "Estonia",
      'EG': "Mesir",
      'ER': "Eritrea",
      'ES': "Sepanyol",
      'ET': "Ethiopia",
      'FI': "Finland",
      'FJ': "Fiji",
      'FM': "Micronesia",
      'FO': "Kepulauan Faroe",
      'GA': "Gabon",
      'GB': "United Kingdom",
      'GD': "Grenada",
      'GE': "Georgia",
      'GG': "Guernsey",
      'GH': "Ghana",
      'GL': "Greenland",
      'GM': "Gambia",
      'GN': "Guinea",
      'GQ': "Guinea Khatulistiwa",
      'GR': "Greece",
      'GS': "Kepulauan Georgia Selatan & Sandwich Selatan",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Guinea Bissau",
      'GY': "Guyana",
      'HK': "Hong Kong SAR China",
      'HM': "Kepulauan Heard & McDonald",
      'HN': "Honduras",
      'HR': "Croatia",
      'HT': "Haiti",
      'HU': "Hungary",
      'ID': "Indonesia",
      'IE': "Ireland",
      'IM': "Isle of Man",
      'IN': "India",
      'IQ': "Iraq",
      'IR': "Iran",
      'IS': "Iceland",
      'IT': "Itali",
      'JE': "Jersey",
      'JM': "Jamaica",
      'JO': "Jordan",
      'JP': "Jepun",
      'KE': "Kenya",
      'KG': "Kyrgyzstan",
      'KH': "Kemboja",
      'KI': "Kiribati",
      'KM': "Comoros",
      'KN': "Saint Kitts dan Nevis",
      'KP': "Korea Utara",
      'KR': "Korea Selatan",
      'KW': "Kuwait",
      'KY': "Kepulauan Cayman",
      'KZ': "Kazakhstan",
      'LA': "Laos",
      'LB': "Lubnan",
      'LC': "Saint Lucia",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberia",
      'LS': "Lesotho",
      'LT': "Lithuania",
      'LU': "Luxembourg",
      'LV': "Latvia",
      'LY': "Libya",
      'MA': "Maghribi",
      'MC': "Monaco",
      'MD': "Moldova",
      'ME': "Montenegro",
      'MF': "Saint Martin",
      'MG': "Madagaskar",
      'MH': "Kepulauan Marshall",
      'MK': "Macedonia Utara",
      'ML': "Mali",
      'MM': "Myanmar (Burma)",
      'MN': "Mongolia",
      'MO': "Macau SAR China",
      'MP': "Kepulauan Mariana Utara",
      'MR': "Mauritania",
      'MS': "Montserrat",
      'MT': "Malta",
      'MU': "Mauritius",
      'MV': "Maldives",
      'MW': "Malawi",
      'MX': "Mexico",
      'MY': "Malaysia",
      'MZ': "Mozambique",
      'NA': "Namibia",
      'NC': "New Caledonia",
      'NE': "Niger",
      'NF': "Pulau Norfolk",
      'NG': "Nigeria",
      'NI': "Nicaragua",
      'NL': "Belanda",
      'NP': "Nepal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "New Zealand",
      'OM': "Oman",
      'PA': "Panama",
      'PE': "Peru",
      'PF': "Polinesia Perancis",
      'PG': "Papua New Guinea",
      'PH': "Filipina",
      'PK': "Pakistan",
      'PL': "Poland",
      'PM': "Saint Pierre dan Miquelon",
      'PN': "Kepulauan Pitcairn",
      'PR': "Puerto Rico",
      'PT': "Portugal",
      'PW': "Palau",
      'PY': "Paraguay",
      'QA': "Qatar",
      'RO': "Romania",
      'RS': "Serbia",
      'RU': "Rusia",
      'RW': "Rwanda",
      'SA': "Arab Saudi",
      'SB': "Kepulauan Solomon",
      'SC': "Seychelles",
      'SD': "Sudan",
      'SE': "Sweden",
      'SG': "Singapura",
      'SH': "Saint Helena",
      'SI': "Slovenia",
      'SK': "Slovakia",
      'SL': "Sierra Leone",
      'SM': "San Marino",
      'SN': "Senegal",
      'SO': "Somalia",
      'SR': "Surinam",
      'SS': "Sudan Selatan",
      'ST': "Sao Tome dan Principe",
      'SV': "El Salvador",
      'SX': "Sint Maarten",
      'SY': "Syria",
      'SZ': "Eswatini",
      'TC': "Kepulauan Turks dan Caicos",
      'TD': "Chad",
      'TF': "Wilayah Selatan Perancis",
      'TG': "Togo",
      'TH': "Thailand",
      'TJ': "Tajikistan",
      'TL': "Timor-Leste",
      'TM': "Turkmenistan",
      'TN': "Tunisia",
      'TO': "Tonga",
      'TR': "Turkiye",
      'TT': "Trinidad dan Tobago",
      'TV': "Tuvalu",
      'TZ': "Tanzania",
      'UA': "Ukraine",
      'UG': "Uganda",
      'US': "Amerika Syarikat",
      'UY': "Uruguay",
      'UZ': "Uzbekistan",
      'VA': "Kota Vatican",
      'VC': "Saint Vincent dan Grenadines",
      'VE': "Venezuela",
      'VG': "Kepulauan Virgin British",
      'VI': "Kepulauan Virgin A.S.",
      'VN': "Vietnam",
      'VU': "Vanuatu",
      'WF': "Wallis dan Futuna",
      'WS': "Samoa",
      'YE': "Yaman",
      'ZA': "Afrika Selatan",
      'ZM': "Zambia",
      'ZW': "Zimbabwe",
    },
    'ru': {
      'AD': "Андорра",
      'AE': "ОАЭ",
      'AF': "Афганистан",
      'AG': "Антигуа и Барбуда",
      'AI': "Ангилья",
      'AL': "Албания",
      'AM': "Армения",
      'AO': "Ангола",
      'AR': "Аргентина",
      'AS': "Американское Самоа",
      'AT': "Австрия",
      'AU': "Австралия",
      'AW': "Аруба",
      'AX': "Аландские о-ва",
      'AZ': "Азербайджан",
      'BA': "Босния и Герцеговина",
      'BB': "Барбадос",
      'BD': "Бангладеш",
      'BE': "Бельгия",
      'BF': "Буркина-Фасо",
      'BG': "Болгария",
      'BH': "Бахрейн",
      'BI': "Бурунди",
      'BJ': "Бенин",
      'BL': "Сен-Бартелеми",
      'BM': "Бермудские о-ва",
      'BN': "Бруней",
      'BO': "Боливия",
      'BR': "Бразилия",
      'BS': "Багамы",
      'BT': "Бутан",
      'BW': "Ботсвана",
      'BY': "Беларусь",
      'BZ': "Белиз",
      'CA': "Канада",
      'CD': "Конго - Киншаса",
      'CF': "Центрально-Африканская Республика",
      'CG': "Конго - Браззавиль",
      'CH': "Швейцария",
      'CI': "Кот-д’Ивуар",
      'CK': "о-ва Кука",
      'CL': "Чили",
      'CM': "Камерун",
      'CN': "Китай",
      'CO': "Колумбия",
      'CR': "Коста-Рика",
      'CU': "Куба",
      'CV': "Кабо-Верде",
      'CW': "Кюрасао",
      'CY': "Кипр",
      'CZ': "Чехия",
      'DE': "Германия",
      'DJ': "Джибути",
      'DK': "Дания",
      'DM': "Доминика",
      'DO': "Доминиканская Республика",
      'DZ': "Алжир",
      'EC': "Эквадор",
      'EE': "Эстония",
      'EG': "Египет",
      'ER': "Эритрея",
      'ES': "Испания",
      'ET': "Эфиопия",
      'FI': "Финляндия",
      'FJ': "Фиджи",
      'FM': "Федеративные Штаты Микронезии",
      'FO': "Фарерские о-ва",
      'GA': "Габон",
      'GB': "Великобритания",
      'GD': "Гренада",
      'GE': "Грузия",
      'GG': "Гернси",
      'GH': "Гана",
      'GL': "Гренландия",
      'GM': "Гамбия",
      'GN': "Гвинея",
      'GQ': "Экваториальная Гвинея",
      'GR': "Греция",
      'GS': "Южная Георгия и Южные Сандвичевы о-ва",
      'GT': "Гватемала",
      'GU': "Гуам",
      'GW': "Гвинея-Бисау",
      'GY': "Гайана",
      'HK': "Гонконг (САР)",
      'HM': "о-ва Херд и Макдональд",
      'HN': "Гондурас",
      'HR': "Хорватия",
      'HT': "Гаити",
      'HU': "Венгрия",
      'ID': "Индонезия",
      'IE': "Ирландия",
      'IM': "о-в Мэн",
      'IN': "Индия",
      'IQ': "Ирак",
      'IR': "Иран",
      'IS': "Исландия",
      'IT': "Италия",
      'JE': "Джерси",
      'JM': "Ямайка",
      'JO': "Иордания",
      'JP': "Япония",
      'KE': "Кения",
      'KG': "Киргизия",
      'KH': "Камбоджа",
      'KI': "Кирибати",
      'KM': "Коморы",
      'KN': "Сент-Китс и Невис",
      'KP': "КНДР",
      'KR': "Республика Корея",
      'KW': "Кувейт",
      'KY': "о-ва Кайман",
      'KZ': "Казахстан",
      'LA': "Лаос",
      'LB': "Ливан",
      'LC': "Сент-Люсия",
      'LI': "Лихтенштейн",
      'LK': "Шри-Ланка",
      'LR': "Либерия",
      'LS': "Лесото",
      'LT': "Литва",
      'LU': "Люксембург",
      'LV': "Латвия",
      'LY': "Ливия",
      'MA': "Марокко",
      'MC': "Монако",
      'MD': "Молдова",
      'ME': "Черногория",
      'MF': "Сен-Мартен",
      'MG': "Мадагаскар",
      'MH': "Маршалловы о-ва",
      'MK': "Северная Македония",
      'ML': "Мали",
      'MM': "Мьянма (Бирма)",
      'MN': "Монголия",
      'MO': "Макао (САР)",
      'MP': "Северные Марианские о-ва",
      'MR': "Мавритания",
      'MS': "Монтсеррат",
      'MT': "Мальта",
      'MU': "Маврикий",
      'MV': "Мальдивы",
      'MW': "Малави",
      'MX': "Мексика",
      'MY': "Малайзия",
      'MZ': "Мозамбик",
      'NA': "Намибия",
      'NC': "Новая Каледония",
      'NE': "Нигер",
      'NF': "о-в Норфолк",
      'NG': "Нигерия",
      'NI': "Никарагуа",
      'NL': "Нидерланды",
      'NP': "Непал",
      'NR': "Науру",
      'NU': "Ниуэ",
      'NZ': "Новая Зеландия",
      'OM': "Оман",
      'PA': "Панама",
      'PE': "Перу",
      'PF': "Французская Полинезия",
      'PG': "Папуа — Новая Гвинея",
      'PH': "Филиппины",
      'PK': "Пакистан",
      'PL': "Польша",
      'PM': "Сен-Пьер и Микелон",
      'PN': "о-ва Питкэрн",
      'PR': "Пуэрто-Рико",
      'PT': "Португалия",
      'PW': "Палау",
      'PY': "Парагвай",
      'QA': "Катар",
      'RO': "Румыния",
      'RS': "Сербия",
      'RU': "Россия",
      'RW': "Руанда",
      'SA': "Саудовская Аравия",
      'SB': "Соломоновы о-ва",
      'SC': "Сейшельские о-ва",
      'SD': "Судан",
      'SE': "Швеция",
      'SG': "Сингапур",
      'SH': "о-в Св. Елены",
      'SI': "Словения",
      'SK': "Словакия",
      'SL': "Сьерра-Леоне",
      'SM': "Сан-Марино",
      'SN': "Сенегал",
      'SO': "Сомали",
      'SR': "Суринам",
      'SS': "Южный Судан",
      'ST': "Сан-Томе и Принсипи",
      'SV': "Сальвадор",
      'SX': "Синт-Мартен",
      'SY': "Сирия",
      'SZ': "Эсватини",
      'TC': "Тёркс и Кайкос",
      'TD': "Чад",
      'TF': "Французские Южные территории",
      'TG': "Того",
      'TH': "Таиланд",
      'TJ': "Таджикистан",
      'TL': "Восточный Тимор",
      'TM': "Туркменистан",
      'TN': "Тунис",
      'TO': "Тонга",
      'TR': "Турция",
      'TT': "Тринидад и Тобаго",
      'TV': "Тувалу",
      'TZ': "Танзания",
      'UA': "Украина",
      'UG': "Уганда",
      'US': "Соединенные Штаты",
      'UY': "Уругвай",
      'UZ': "Узбекистан",
      'VA': "Ватикан",
      'VC': "Сент-Винсент и Гренадины",
      'VE': "Венесуэла",
      'VG': "Виргинские о-ва (Великобритания)",
      'VI': "Виргинские о-ва (США)",
      'VN': "Вьетнам",
      'VU': "Вануату",
      'WF': "Уоллис и Футуна",
      'WS': "Самоа",
      'YE': "Йемен",
      'ZA': "Южно-Африканская Республика",
      'ZM': "Замбия",
      'ZW': "Зимбабве",
    },
    'tr': {
      'AD': "Andorra",
      'AE': "Birleşik Arap Emirlikleri",
      'AF': "Afganistan",
      'AG': "Antigua ve Barbuda",
      'AI': "Anguilla",
      'AL': "Arnavutluk",
      'AM': "Ermenistan",
      'AO': "Angola",
      'AR': "Arjantin",
      'AS': "Amerikan Samoası",
      'AT': "Avusturya",
      'AU': "Avustralya",
      'AW': "Aruba",
      'AX': "Åland Adaları",
      'AZ': "Azerbaycan",
      'BA': "Bosna-Hersek",
      'BB': "Barbados",
      'BD': "Bangladeş",
      'BE': "Belçika",
      'BF': "Burkina Faso",
      'BG': "Bulgaristan",
      'BH': "Bahreyn",
      'BI': "Burundi",
      'BJ': "Benin",
      'BL': "Saint Barthelemy",
      'BM': "Bermuda",
      'BN': "Brunei",
      'BO': "Bolivya",
      'BR': "Brezilya",
      'BS': "Bahamalar",
      'BT': "Butan",
      'BW': "Botsvana",
      'BY': "Belarus",
      'BZ': "Belize",
      'CA': "Kanada",
      'CD': "Kongo - Kinşasa",
      'CF': "Orta Afrika Cumhuriyeti",
      'CG': "Kongo - Brazavil",
      'CH': "İsviçre",
      'CI': "Côte d’Ivoire",
      'CK': "Cook Adaları",
      'CL': "Şili",
      'CM': "Kamerun",
      'CN': "Çin",
      'CO': "Kolombiya",
      'CR': "Kosta Rika",
      'CU': "Küba",
      'CV': "Cabo Verde",
      'CW': "Curaçao",
      'CY': "Kıbrıs",
      'CZ': "Çekya",
      'DE': "Almanya",
      'DJ': "Cibuti",
      'DK': "Danimarka",
      'DM': "Dominika",
      'DO': "Dominik Cumhuriyeti",
      'DZ': "Cezayir",
      'EC': "Ekvador",
      'EE': "Estonya",
      'EG': "Mısır",
      'ER': "Eritre",
      'ES': "İspanya",
      'ET': "Etiyopya",
      'FI': "Finlandiya",
      'FJ': "Fiji",
      'FM': "Mikronezya",
      'FO': "Faroe Adaları",
      'GA': "Gabon",
      'GB': "Birleşik Krallık",
      'GD': "Grenada",
      'GE': "Gürcistan",
      'GG': "Guernsey",
      'GH': "Gana",
      'GL': "Grönland",
      'GM': "Gambiya",
      'GN': "Gine",
      'GQ': "Ekvator Ginesi",
      'GR': "Yunanistan",
      'GS': "Güney Georgia ve Güney Sandwich Adaları",
      'GT': "Guatemala",
      'GU': "Guam",
      'GW': "Gine-Bissau",
      'GY': "Guyana",
      'HK': "Çin Hong Kong ÖİB",
      'HM': "Heard Adası ve McDonald Adaları",
      'HN': "Honduras",
      'HR': "Hırvatistan",
      'HT': "Haiti",
      'HU': "Macaristan",
      'ID': "Endonezya",
      'IE': "İrlanda",
      'IM': "Man Adası",
      'IN': "Hindistan",
      'IQ': "Irak",
      'IR': "İran",
      'IS': "İzlanda",
      'IT': "İtalya",
      'JE': "Jersey",
      'JM': "Jamaika",
      'JO': "Ürdün",
      'JP': "Japonya",
      'KE': "Kenya",
      'KG': "Kırgızistan",
      'KH': "Kamboçya",
      'KI': "Kiribati",
      'KM': "Komorlar",
      'KN': "Saint Kitts ve Nevis",
      'KP': "Kuzey Kore",
      'KR': "Güney Kore",
      'KW': "Kuveyt",
      'KY': "Cayman Adaları",
      'KZ': "Kazakistan",
      'LA': "Laos",
      'LB': "Lübnan",
      'LC': "Saint Lucia",
      'LI': "Liechtenstein",
      'LK': "Sri Lanka",
      'LR': "Liberya",
      'LS': "Lesotho",
      'LT': "Litvanya",
      'LU': "Lüksemburg",
      'LV': "Letonya",
      'LY': "Libya",
      'MA': "Fas",
      'MC': "Monako",
      'MD': "Moldova",
      'ME': "Karadağ",
      'MF': "Saint Martin",
      'MG': "Madagaskar",
      'MH': "Marshall Adaları",
      'MK': "Kuzey Makedonya",
      'ML': "Mali",
      'MM': "Myanmar (Burma)",
      'MN': "Moğolistan",
      'MO': "Çin Makao ÖİB",
      'MP': "Kuzey Mariana Adaları",
      'MR': "Moritanya",
      'MS': "Montserrat",
      'MT': "Malta",
      'MU': "Mauritius",
      'MV': "Maldivler",
      'MW': "Malavi",
      'MX': "Meksika",
      'MY': "Malezya",
      'MZ': "Mozambik",
      'NA': "Namibya",
      'NC': "Yeni Kaledonya",
      'NE': "Nijer",
      'NF': "Norfolk Adası",
      'NG': "Nijerya",
      'NI': "Nikaragua",
      'NL': "Hollanda",
      'NP': "Nepal",
      'NR': "Nauru",
      'NU': "Niue",
      'NZ': "Yeni Zelanda",
      'OM': "Umman",
      'PA': "Panama",
      'PE': "Peru",
      'PF': "Fransız Polinezyası",
      'PG': "Papua Yeni Gine",
      'PH': "Filipinler",
      'PK': "Pakistan",
      'PL': "Polonya",
      'PM': "Saint Pierre ve Miquelon",
      'PN': "Pitcairn Adaları",
      'PR': "Porto Riko",
      'PT': "Portekiz",
      'PW': "Palau",
      'PY': "Paraguay",
      'QA': "Katar",
      'RO': "Romanya",
      'RS': "Sırbistan",
      'RU': "Rusya",
      'RW': "Ruanda",
      'SA': "Suudi Arabistan",
      'SB': "Solomon Adaları",
      'SC': "Seyşeller",
      'SD': "Sudan",
      'SE': "İsveç",
      'SG': "Singapur",
      'SH': "Saint Helena",
      'SI': "Slovenya",
      'SK': "Slovakya",
      'SL': "Sierra Leone",
      'SM': "San Marino",
      'SN': "Senegal",
      'SO': "Somali",
      'SR': "Surinam",
      'SS': "Güney Sudan",
      'ST': "Sao Tome ve Principe",
      'SV': "El Salvador",
      'SX': "Sint Maarten",
      'SY': "Suriye",
      'SZ': "Esvatini",
      'TC': "Turks ve Caicos Adaları",
      'TD': "Çad",
      'TF': "Fransız Güney Toprakları",
      'TG': "Togo",
      'TH': "Tayland",
      'TJ': "Tacikistan",
      'TL': "Timor-Leste",
      'TM': "Türkmenistan",
      'TN': "Tunus",
      'TO': "Tonga",
      'TR': "Türkiye",
      'TT': "Trinidad ve Tobago",
      'TV': "Tuvalu",
      'TZ': "Tanzanya",
      'UA': "Ukrayna",
      'UG': "Uganda",
      'US': "Amerika Birleşik Devletleri",
      'UY': "Uruguay",
      'UZ': "Özbekistan",
      'VA': "Vatikan",
      'VC': "Saint Vincent ve Grenadinler",
      'VE': "Venezuela",
      'VG': "Britanya Virjin Adaları",
      'VI': "ABD Virjin Adaları",
      'VN': "Vietnam",
      'VU': "Vanuatu",
      'WF': "Wallis ve Futuna",
      'WS': "Samoa",
      'YE': "Yemen",
      'ZA': "Güney Afrika",
      'ZM': "Zambiya",
      'ZW': "Zimbabve",
    },
    'ur': {
      'AD': "انڈورا",
      'AE': "متحدہ عرب امارات",
      'AF': "افغانستان",
      'AG': "انٹیگوا اور باربودا",
      'AI': "انگوئیلا",
      'AL': "البانیہ",
      'AM': "آرمینیا",
      'AO': "انگولا",
      'AR': "ارجنٹینا",
      'AS': "امریکی ساموآ",
      'AT': "آسٹریا",
      'AU': "آسٹریلیا",
      'AW': "اروبا",
      'AX': "آلینڈ آئلینڈز",
      'AZ': "آذربائیجان",
      'BA': "بوسنیا اور ہرزیگووینا",
      'BB': "بارباڈوس",
      'BD': "بنگلہ دیش",
      'BE': "بیلجیم",
      'BF': "برکینا فاسو",
      'BG': "بلغاریہ",
      'BH': "بحرین",
      'BI': "برونڈی",
      'BJ': "بینن",
      'BL': "سینٹ برتھلیمی",
      'BM': "برمودا",
      'BN': "برونائی",
      'BO': "بولیویا",
      'BR': "برازیل",
      'BS': "بہاماس",
      'BT': "بھوٹان",
      'BW': "بوتسوانا",
      'BY': "بیلاروس",
      'BZ': "بیلائز",
      'CA': "کینیڈا",
      'CD': "کانگو - کنشاسا",
      'CF': "وسط افریقی جمہوریہ",
      'CG': "کانگو - برازاویلے",
      'CH': "سوئٹزر لینڈ",
      'CI': "کوٹ ڈی آئیوری",
      'CK': "کک آئلینڈز",
      'CL': "چلی",
      'CM': "کیمرون",
      'CN': "چین",
      'CO': "کولمبیا",
      'CR': "کوسٹا ریکا",
      'CU': "کیوبا",
      'CV': "کیپ ورڈی",
      'CW': "کیوراکاؤ",
      'CY': "قبرص",
      'CZ': "چیکیا",
      'DE': "جرمنی",
      'DJ': "جبوتی",
      'DK': "ڈنمارک",
      'DM': "ڈومنیکا",
      'DO': "جمہوریہ ڈومينيکن",
      'DZ': "الجیریا",
      'EC': "ایکواڈور",
      'EE': "اسٹونیا",
      'EG': "مصر",
      'ER': "اریٹیریا",
      'ES': "ہسپانیہ",
      'ET': "ایتھوپیا",
      'FI': "فن لینڈ",
      'FJ': "فجی",
      'FM': "مائکرونیشیا",
      'FO': "جزائر فارو",
      'GA': "گیبون",
      'GB': "سلطنت متحدہ",
      'GD': "گریناڈا",
      'GE': "جارجیا",
      'GG': "گوئرنسی",
      'GH': "گھانا",
      'GL': "گرین لینڈ",
      'GM': "گیمبیا",
      'GN': "گنی",
      'GQ': "استوائی گیانا",
      'GR': "یونان",
      'GS': "جنوبی جارجیا اور جنوبی سینڈوچ جزائر",
      'GT': "گواٹے مالا",
      'GU': "گوام",
      'GW': "گنی بساؤ",
      'GY': "گیانا",
      'HK': "ہانگ کانگ SAR چین",
      'HM': "ہیرڈ جزیرہ و میکڈولینڈ جزائر",
      'HN': "ہونڈاروس",
      'HR': "کروشیا",
      'HT': "ہیٹی",
      'HU': "ہنگری",
      'ID': "انڈونیشیا",
      'IE': "آئرلینڈ",
      'IM': "آئل آف مین",
      'IN': "بھارت",
      'IQ': "عراق",
      'IR': "ایران",
      'IS': "آئس لینڈ",
      'IT': "اٹلی",
      'JE': "جرسی",
      'JM': "جمائیکا",
      'JO': "اردن",
      'JP': "جاپان",
      'KE': "کینیا",
      'KG': "کرغزستان",
      'KH': "کمبوڈیا",
      'KI': "کریباتی",
      'KM': "کوموروس",
      'KN': "سینٹ کٹس اور نیویس",
      'KP': "شمالی کوریا",
      'KR': "جنوبی کوریا",
      'KW': "کویت",
      'KY': "کیمین آئلینڈز",
      'KZ': "قزاخستان",
      'LA': "لاؤس",
      'LB': "لبنان",
      'LC': "سینٹ لوسیا",
      'LI': "لیشٹنسٹائن",
      'LK': "سری لنکا",
      'LR': "لائبیریا",
      'LS': "لیسوتھو",
      'LT': "لیتھونیا",
      'LU': "لکسمبرگ",
      'LV': "لٹویا",
      'LY': "لیبیا",
      'MA': "مراکش",
      'MC': "موناکو",
      'MD': "مالدووا",
      'ME': "مونٹے نیگرو",
      'MF': "سینٹ مارٹن",
      'MG': "مڈغاسکر",
      'MH': "مارشل آئلینڈز",
      'MK': "شمالی مقدونیہ",
      'ML': "مالی",
      'MM': "میانمار (برما)",
      'MN': "منگولیا",
      'MO': "مکاؤ SAR چین",
      'MP': "شمالی ماریانا آئلینڈز",
      'MR': "موریطانیہ",
      'MS': "مونٹسیراٹ",
      'MT': "مالٹا",
      'MU': "ماریشس",
      'MV': "مالدیپ",
      'MW': "ملاوی",
      'MX': "میکسیکو",
      'MY': "ملائشیا",
      'MZ': "موزمبیق",
      'NA': "نامیبیا",
      'NC': "نیو کلیڈونیا",
      'NE': "نائجر",
      'NF': "نارفوک آئلینڈ",
      'NG': "نائجیریا",
      'NI': "نکاراگووا",
      'NL': "نیدر لینڈز",
      'NP': "نیپال",
      'NR': "نؤرو",
      'NU': "نیئو",
      'NZ': "نیوزی لینڈ",
      'OM': "عمان",
      'PA': "پانامہ",
      'PE': "پیرو",
      'PF': "فرانسیسی پولینیشیا",
      'PG': "پاپوآ نیو گنی",
      'PH': "فلپائن",
      'PK': "پاکستان",
      'PL': "پولینڈ",
      'PM': "سینٹ پیئر اور میکلیئون",
      'PN': "پٹکائرن جزائر",
      'PR': "پیورٹو ریکو",
      'PT': "پرتگال",
      'PW': "پلاؤ",
      'PY': "پیراگوئے",
      'QA': "قطر",
      'RO': "رومانیہ",
      'RS': "سربیا",
      'RU': "روس",
      'RW': "روانڈا",
      'SA': "سعودی عرب",
      'SB': "سولومن آئلینڈز",
      'SC': "سشلیز",
      'SD': "سوڈان",
      'SE': "سویڈن",
      'SG': "سنگاپور",
      'SH': "سینٹ ہیلینا",
      'SI': "سلووینیا",
      'SK': "سلوواکیہ",
      'SL': "سیرالیون",
      'SM': "سان مارینو",
      'SN': "سینیگل",
      'SO': "صومالیہ",
      'SR': "سورینام",
      'SS': "جنوبی سوڈان",
      'ST': "ساؤ ٹومے اور پرنسپے",
      'SV': "ال سلواڈور",
      'SX': "سنٹ مارٹن",
      'SY': "شام",
      'SZ': "سواتنی",
      'TC': "ٹرکس اور کیکوس جزائر",
      'TD': "چاڈ",
      'TF': "فرانسیسی جنوبی خطے",
      'TG': "ٹوگو",
      'TH': "تھائی لینڈ",
      'TJ': "تاجکستان",
      'TL': "تیمور لیسٹ",
      'TM': "ترکمانستان",
      'TN': "تونس",
      'TO': "ٹونگا",
      'TR': "ترکیہ",
      'TT': "ترینیداد اور ٹوباگو",
      'TV': "ٹووالو",
      'TZ': "تنزانیہ",
      'UA': "یوکرین",
      'UG': "یوگنڈا",
      'US': "ریاست ہائے متحدہ امریکہ",
      'UY': "یوروگوئے",
      'UZ': "ازبکستان",
      'VA': "ویٹیکن سٹی",
      'VC': "سینٹ ونسنٹ اور گرینیڈائنز",
      'VE': "وینزوئیلا",
      'VG': "برٹش ورجن آئلینڈز",
      'VI': "امریکی ورجن آئلینڈز",
      'VN': "ویتنام",
      'VU': "وینوآٹو",
      'WF': "ویلیز اور فیوٹیونا",
      'WS': "ساموآ",
      'YE': "یمن",
      'ZA': "جنوبی افریقہ",
      'ZM': "زامبیا",
      'ZW': "زمبابوے",
    },
  };

  static String? localized(String? code, String locale) {
    if (code == null || code.isEmpty) return null;
    final normalized = code.toUpperCase();
    final language = locale.split(RegExp(r'[-_]')).first.toLowerCase();
    return _names[language]?[normalized] ??
        _names['en']?[normalized] ??
        normalized;
  }
}
