import 'package:huda/core/services/prayer_times_calculator.dart';
import 'package:huda/l10n/app_localizations.dart';

String prayerCalendarMethodLabel(AppLocalizations l10n, String token) {
  switch (token) {
    case PrayerTimesCalculator.autoMethodToken:
      return l10n.prayerMethodAuto;
    case 'ummAlQura':
      return l10n.prayerMethodUmmAlQura;
    case 'muslimWorldLeague':
      return l10n.prayerMethodMuslimWorldLeague;
    case 'egyptian':
      return l10n.prayerMethodEgyptian;
    case 'karachi':
      return l10n.prayerMethodKarachi;
    case 'northAmerica':
      return l10n.prayerMethodNorthAmerica;
    case 'emirates':
      return l10n.prayerMethodEmirates;
    case 'dubai':
      return l10n.prayerMethodDubai;
    case 'qatar':
      return l10n.prayerMethodQatar;
    case 'kuwait':
      return l10n.prayerMethodKuwait;
    case 'oman':
      return l10n.prayerMethodOman;
    case 'omanMuscat':
      return l10n.prayerMethodOmanMuscat;
    case 'jordan':
      return l10n.prayerMethodJordan;
    case 'palestine':
      return l10n.prayerMethodPalestine;
    case 'syria':
      return l10n.prayerMethodSyria;
    case 'iraq':
      return l10n.prayerMethodIraq;
    case 'morocco':
      return l10n.prayerMethodMorocco;
    case 'azrou':
      return l10n.prayerMethodAzrou;
    case 'algeria':
      return l10n.prayerMethodAlgeria;
    case 'tunisia':
      return l10n.prayerMethodTunisia;
    case 'libya':
      return l10n.prayerMethodLibya;
    case 'sudan':
      return l10n.prayerMethodSudan;
    case 'turkey':
      return l10n.prayerMethodTurkey;
    case 'malaysia':
      return l10n.prayerMethodMalaysia;
    case 'malaysia2':
      return l10n.prayerMethodMalaysia2;
    case 'indonesia':
      return l10n.prayerMethodIndonesia;
    case 'kazakhstan':
      return l10n.prayerMethodKazakhstan;
    case 'tajikistan':
      return l10n.prayerMethodTajikistan;
    case 'maldives':
      return l10n.prayerMethodMaldives;
    case 'southKorea':
      return l10n.prayerMethodSouthKorea;
    case 'uoif':
      return l10n.prayerMethodUoif;
    case 'paris':
      return l10n.prayerMethodParis;
    case 'toulouse':
      return l10n.prayerMethodToulouse;
    case 'lyon':
      return l10n.prayerMethodLyon;
    case 'orleans':
      return l10n.prayerMethodOrleans;
    case 'moscow':
      return l10n.prayerMethodMoscow;
    case 'czech':
      return l10n.prayerMethodCzech;
    case 'switzerland':
      return l10n.prayerMethodSwitzerland;
    case 'fribourg':
      return l10n.prayerMethodFribourg;
    case 'belgium':
      return l10n.prayerMethodBelgium;
    case 'luxembourg':
      return l10n.prayerMethodLuxembourg;
    case 'austria':
      return l10n.prayerMethodAustria;
    case 'london':
      return l10n.prayerMethodLondon;
    case 'birmingham':
      return l10n.prayerMethodBirmingham;
    case 'blackburn':
      return l10n.prayerMethodBlackburn;
    case 'aachen':
      return l10n.prayerMethodAachen;
    case 'munchen':
      return l10n.prayerMethodMunchen;
    case 'potsdam':
      return l10n.prayerMethodPotsdam;
    case 'nurnberg':
      return l10n.prayerMethodNurnberg;
    case 'rotterdam':
      return l10n.prayerMethodRotterdam;
    case 'dordrecht':
      return l10n.prayerMethodDordrecht;
    case 'eindhoven':
      return l10n.prayerMethodEindhoven;
    case 'montreal':
      return l10n.prayerMethodMontreal;
    case 'windsor':
      return l10n.prayerMethodWindsor;
    case 'calgary':
      return l10n.prayerMethodCalgary;
    case 'mississauga':
      return l10n.prayerMethodMississauga;
    case 'other':
      return l10n.prayerMethodOther;
    default:
      return token;
  }
}
