default_platform(:mac)

platform :mac do
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_P8"],
      is_key_content_base64: true
    )

    upload_to_app_store(
      api_key: api_key,
      pkg: "../build/macos/Huda-macOS.pkg",
      skip_metadata: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false,
      platform: "osx"
    )
  end
end
